# Generated by Django 4.0 on 2021-12-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auctionproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionproduct',
            old_name='product_descruption',
            new_name='product_description',
        ),
    ]
