# Generated by Django 4.0 on 2021-12-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_product_descruption_auctionproduct_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionproduct',
            options={'ordering': ['-created_at']},
        ),
    ]
